### ISSUE TITLE
Version 7.5.1

### ISSUE THREAD

**Issue by mseidlx** [ommsolutions/kibana_ext_metrics_vis#21]
I tried adjusting the package.json to the new version, but unfortunately that didn't do the trick for me. Would be great to have this plugin for 7.5.1

**Comment by olsn** [comment]
Are there any additional error-logs?
I currently did not yet check upon possible breaking changes, we will do when time allows or when we require to update.

**Comment by OhmedS** [comment]
Hello, I have the same issue as @MSeidl93. Im using Kibana 7.5.1 inside of a Docker-Container.
I also adjusted the package.json but I still encounterd an error (I installed another plugin before and it worked). Here are the logs and also my Dockerfile. 

**Dockefile**

FROM docker.elastic.co/kibana/kibana:7.5.1

RUN ./bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.7.0/enhanced-table-1.7.0_7.5.1.zip

COPY kibana_ext_metrics_vis.zip '/opt/kibana/kibana_ext_metrics_vis/kibana_ext_metrics_vis.zip'

RUN ./bin/kibana-plugin install file:///opt/kibana/kibana_ext_metrics_vis/kibana_ext_metrics_vis.zip

**Logoutput**

Building kibana
Step 1/4 : FROM docker.elastic.co/kibana/kibana:7.5.1
 ---> 2d043e33afa4
Step 2/4 : RUN ./bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.7.0/enhanced-table-1.7.0_7.5.1.zip
 ---> Running in 45a48a8c7e97
Attempting to transfer from https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.7.0/enhanced-table-1.7.0_7.5.1.zip
Transferring 715896 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete
Removing intermediate container 45a48a8c7e97
 ---> fe5982835c5e
Step 3/4 : COPY kibana_ext_metrics_vis.zip '/opt/kibana/kibana_ext_metrics_vis/kibana_ext_metrics_vis.zip'
 ---> bca3418e733d
Step 4/4 : RUN ./bin/kibana-plugin install file:///opt/kibana/kibana_ext_metrics_vis/kibana_ext_metrics_vis.zip
 ---> Running in a169bcde57b0
Attempting to transfer from file:///opt/kibana/kibana_ext_metrics_vis/kibana_ext_metrics_vis.zip
Transferring 1570017 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "This plugin is using `link:` dependencies for non-Kibana packages"
ERROR: Service 'kibana' failed to build: The command '/bin/sh -c ./bin/kibana-plugin install file:///opt/kibana/kibana_ext_metrics_vis/kibana_ext_metrics_vis.zip' returned a non-zero code: 70

**Comment by sonali-goswami** [comment]
Hi ,

I am also using kibana 7.5.1, I want to find ratio of two metrics real time. But there is no plugin available for 7.5.1, Please help.

**Comment by mseidlx** [comment]
> Are there any additional error-logs?
> I currently did not yet check upon possible breaking changes, we will do when time allows or when we require to update.

Do the error logs help you to nail down the issue? Any help would be very much appreciated!

**Comment by difranca** [comment]
> Do the error logs help you to nail down the issue? Any help would be very much appreciated!

I tried to install on a Bitnami OSS distribution and I had the following issue:

    ERROR in ./plugins/extended_metric_vis/public/legacy.js
    Module not found: Error: Can't resolve 'plugins/visualizations' in '/opt/bitnami/kibana/plugins/extended_metric_vis/public'

    ERROR in ./plugins/extended_metric_vis/public/metric_vis_type.js
    Module not found: Error: Can't resolve 'plugins/visualizations' in '/opt/bitnami/kibana/plugins/extended_metric_vis/public'

    ERROR in ./plugins/extended_metric_vis/public/shim/metric_vis_legacy_module.js
    Module not found: Error: Can't resolve 'ui/directives/inequality' in '/opt/bitnami/kibana/plugins/extended_metric_vis/public/shim'

**Comment by masterx0** [comment]
> lowing issu

happend to meet the same error in kibana7.6.0, pls update this plugin !!!

**Comment by ModestinoAndre** [comment]
I installed it on Kibana 7.6.1, but when Kibana is optimizing plug-ins, it shows the following error:

**ERROR in ./plugins/extended_metric_vis/public/shim/metric_vis_legacy_module.js
 Module not found: Error: Can't resolve 'ui/directives/inequality'**

`{"type":"log","@timestamp":"2020-10-13T10:44:52Z","tags":["fatal","root"],"pid":2739,"message":"{ Error: Optimizations failure.\n   9263 modules\n    \n    ERROR in ./plugins/extended_metric_vis/public/shim/metric_vis_legacy_module.js\n    Module not found: Error: Can't resolve 'ui/directives/inequality' in '/usr/share/kibana/plugins/extended_metric_vis/public/shim'\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:436:26)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n    at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:257:39)\n    at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:273:13)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:271:21)\n    at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:681:15)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:678:31)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1423:35)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n  cause:\n   { Error: Optimizations failure.\n      9263 modules\n       \n       ERROR in ./plugins/extended_metric_vis/public/shim/metric_vis_legacy_module.js\n       Module not found: Error: Can't resolve 'ui/directives/inequality' in '/usr/share/kibana/plugins/extended_metric_vis/public/shim'\n   \n       at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:436:26)\n       at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n       at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:257:39)\n       at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:273:13)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:271:21)\n       at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:681:15)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:678:31)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1423:35)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n     data:\n      { errors: [Array],\n        warnings: [],\n        version: '4.41.0',\n        hash: 'f0e482d38e8028ff4c59',\n        time: 169513,\n        builtAt: 1602585892320,\n        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n        outputPath: '/usr/share/kibana/optimize/bundles',\n        assetsByChunkName: [Object],\n        assets: [Array],\n        filteredAssets: 0,\n        entrypoints: [Object],\n        namedChunkGroups: [Object],\n        chunks: [Array],\n        modules: [Array],\n        filteredModules: 0,\n        logging: [Object],\n        children: [Array] },\n     isBoom: true,\n     isServer: true,\n     output: { statusCode: 500, payload: [Object], headers: {} },\n     reformat: [Function],\n     typeof: [Function: internal] },\n  isOperational: true,\n  data:\n   { errors:\n      [ './plugins/extended_metric_vis/public/shim/metric_vis_legacy_module.js\\nModule not found: Error: Can\\'t resolve \\'ui/directives/inequality\\' in \\'/usr/share/kibana/plugins/extended_metric_vis/public/shim\\'\\nresolve \\'ui/directives/inequality\\' in \\'/usr/share/kibana/plugins/extended_metric_vis/public/shim\\'\\n  Parsed request is a module\\n  using description file: /usr/share/kibana/plugins/extended_metric_vis/package.json (relative path: ./public/shim)\\n    aliased with mapping \\'ui\\': \\'/usr/share/kibana/src/legacy/ui/public\\' to \\'/usr/share/kibana/src/legacy/ui/public/directives/inequality\\'\\n      using description file: /usr/share/kibana/plugins/extended_metric_vis/package.json (relative path: ./public/shim)\\n        Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n        using description file: /usr/share/kibana/package.json (relative path: ./src/legacy/ui/public/directives/inequality)\\n          no extension\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/directives/inequality doesn\\'t exist\\n          .js\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/directives/inequality.js doesn\\'t exist\\n          .ts\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/directives/inequality.ts doesn\\'t exist\\n          .tsx\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/directives/inequality.tsx doesn\\'t exist\\n          .json\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/directives/inequality.json doesn\\'t exist\\n          as directory\\n            /usr/share/kibana/src/legacy/ui/public/directives/inequality doesn\\'t exist\\n[/usr/share/kibana/src/legacy/ui/public/directives/inequality]\\n[/usr/share/kibana/src/legacy/ui/public/directives/inequality.js]\\n[/usr/share/kibana/src/legacy/ui/public/directives/inequality.ts]\\n[/usr/share/kibana/src/legacy/ui/public/directives/inequality.tsx]\\n[/usr/share/kibana/src/legacy/ui/public/directives/inequality.json]\\n @ ./plugins/extended_metric_vis/public/shim/metric_vis_legacy_module.js 12:0-35\\n @ ./plugins/extended_metric_vis/public/shim/legacy_dependencies_plugin.js\\n @ ./plugins/extended_metric_vis/public/shim/index.js\\n @ ./plugins/extended_metric_vis/public/legacy.js\\n @ ./node_modules/val-loader/dist/cjs.js!./src/optimize/create_ui_exports_module.js?{\"type\":\"hacks\",\"modules\":[\"plugins/xpack_main/hacks/check_xpack_info_change\",\"plugins/monitoring/hacks/toggle_app_link_in_nav\",\"plugins/spaces/legacy\",\"plugins/security/hacks/on_session_timeout\",\"plugins/security/hacks/on_unauthorized_response\",\"plugins/security/hacks/register_account_management_app\",\"plugins/ml/application/hacks/toggle_app_link_in_nav\",\"plugins/canvas/lib/window_error_handler.js\",\"/usr/share/kibana/x-pack/legacy/plugins/kuery_autocomplete/public/legacy\",\"/usr/share/kibana/plugins/extended_metric_vis/public/legacy\",\"plugins/kibana/discover\",\"plugins/kibana/dev_tools\",\"plugins/kibana/visualize\",\"/usr/share/kibana/src/legacy/core_plugins/input_control_vis/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/region_map/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/tile_map/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/timelion/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/vis_type_markdown/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/vis_type_timeseries/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/vis_type_table/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/vis_type_metric/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/vis_type_tagcloud/public/legacy\",\"/usr/share/kibana/src/legacy/core_plugins/vis_type_vega/public/legacy\"]}\\n @ ./src/legacy/ui/public/chrome/chrome.js\\n @ ./src/legacy/ui/public/chrome/index.js\\n @ ./x-pack/legacy/plugins/monitoring/public/monitoring.js\\n @ ./optimize/bundles/monitoring.entry.js' ],\n     warnings: [],\n     version: '4.41.0',\n     hash: 'f0e482d38e8028ff4c59',\n     time: 169513,\n     builtAt: 1602585892320,\n     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n     outputPath: '/usr/share/kibana/optimize/bundles',\n     assetsByChunkName:\n     `

Anyone can help?
